# Generated by Django 3.0.3 on 2023-03-03 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RDM', '0003_auto_20200113_1422'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
