# Generated by Django 2.1.7 on 2019-08-23 10:37

import api.models
from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.PositiveIntegerField()),
                ('L', models.FloatField(default=0)),
                ('Ch', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20000), default=api.models.df_ch3, size=None)),
                ('Qg', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=api.models.df_fl3, size=None)),
                ('Ql', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=api.models.df_fl3, size=None)),
                ('Rg', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=api.models.df_fl3, size=None)),
                ('Rl', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=api.models.df_fl3, size=None)),
                ('EF', django.contrib.postgres.fields.jsonb.JSONField(default=api.models.df_json)),
                ('DP', django.contrib.postgres.fields.jsonb.JSONField(default=api.models.df_json)),
                ('S', django.contrib.postgres.fields.jsonb.JSONField(default=api.models.df_json)),
                ('EFm', django.contrib.postgres.fields.jsonb.JSONField(default=api.models.df_json)),
                ('DPm', django.contrib.postgres.fields.jsonb.JSONField(default=api.models.df_json)),
                ('Sm', django.contrib.postgres.fields.jsonb.JSONField(default=api.models.df_json)),
            ],
        ),
        migrations.CreateModel(
            name='Distributed_Load',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('Axes', models.CharField(choices=[('G', 'Global'), ('L', 'Local')], default='G', max_length=1)),
                ('features', django.contrib.postgres.fields.jsonb.JSONField()),
                ('bars', models.ManyToManyField(blank=True, related_name='dls', to='api.Bar')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('YM', models.FloatField()),
                ('Density', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.PositiveIntegerField()),
                ('X', models.FloatField()),
                ('Z', models.FloatField()),
                ('Fn', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=api.models.df_fl3, size=None)),
                ('Dp', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=api.models.df_fl3, size=None)),
                ('Rc', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=api.models.df_fl3, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Point_Load',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('FX', models.FloatField(default=0)),
                ('FZ', models.FloatField(default=0)),
                ('CY', models.FloatField(default=0)),
                ('nodes', models.ManyToManyField(blank=True, related_name='pls', to='api.Node')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('auth', models.CharField(choices=[('private', 'private'), ('public', 'public')], default='private', max_length=10)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('UX1', models.BooleanField()),
                ('UZ1', models.BooleanField()),
                ('RY1', models.BooleanField()),
                ('UX2', models.BooleanField()),
                ('UZ2', models.BooleanField()),
                ('RY2', models.BooleanField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='api.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('Ax', models.FloatField()),
                ('Iy', models.FloatField()),
                ('H', models.FloatField()),
                ('Cy', models.FloatField()),
                ('type', models.CharField(default='Custom', max_length=200)),
                ('features', django.contrib.postgres.fields.jsonb.JSONField()),
                ('material', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='sections', to='api.Material')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='api.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('UX', models.BooleanField()),
                ('UZ', models.BooleanField()),
                ('RY', models.BooleanField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supports', to='api.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isDone', models.BooleanField()),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='point_load',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pls', to='api.Project'),
        ),
        migrations.AddField(
            model_name='node',
            name='Support',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='nodes', to='api.Support'),
        ),
        migrations.AddField(
            model_name='node',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='api.Project'),
        ),
        migrations.AddField(
            model_name='material',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='api.Project'),
        ),
        migrations.AddField(
            model_name='distributed_load',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dls', to='api.Project'),
        ),
        migrations.AddField(
            model_name='bar',
            name='N1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='N1', to='api.Node'),
        ),
        migrations.AddField(
            model_name='bar',
            name='N2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='N2', to='api.Node'),
        ),
        migrations.AddField(
            model_name='bar',
            name='Release',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='bars', to='api.Release'),
        ),
        migrations.AddField(
            model_name='bar',
            name='Section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='bars', to='api.Section'),
        ),
        migrations.AddField(
            model_name='bar',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bars', to='api.Project'),
        ),
        migrations.AlterUniqueTogether(
            name='support',
            unique_together={('name', 'project')},
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('name', 'project')},
        ),
        migrations.AlterUniqueTogether(
            name='release',
            unique_together={('name', 'project')},
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('name', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='point_load',
            unique_together={('name', 'project')},
        ),
        migrations.AlterUniqueTogether(
            name='node',
            unique_together={('name', 'project')},
        ),
        migrations.AlterUniqueTogether(
            name='material',
            unique_together={('name', 'project')},
        ),
        migrations.AlterUniqueTogether(
            name='distributed_load',
            unique_together={('name', 'project')},
        ),
        migrations.AlterUniqueTogether(
            name='bar',
            unique_together={('name', 'project')},
        ),
    ]
