# Generated by Django 2.2.6 on 2019-10-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190925_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='type',
            field=models.CharField(choices=[('Rectangular', 'Rectangular'), ('Rectangular_Hollow', 'Rectangular_Hollow'), ('Circular', 'Circular'), ('Circular_Hollow', 'Circular_Hollow'), ('T_Section', 'T_Section'), ('I_Section', 'I_Section'), ('Custom', 'Custom')], default='Custom', max_length=20),
        ),
    ]
