# Generated by Django 2.2.6 on 2019-10-10 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20191009_0716'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Point_Load',
            new_name='Pl',
        ),
    ]
