# Generated by Django 2.2.6 on 2019-10-11 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20191010_1711'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Distributed_Load',
            new_name='Dl',
        ),
    ]
